Repository hassio-addons/addon-nut, pull requests merged in 2021-02, with the labels that each got.

#72 📚 Update docs to reflect integration
  nut/DOCS.md
Labels: documentation

#70 Upgrade add-on base image to 9.1.2
  nut/Dockerfile
  nut/build.json
Labels: dependencies

#83 🔨 Enable udev in config
  nut/config.json
Labels: maintenance

#86 🔨 Add sys_rawio to config
  nut/config.json
Labels: maintenance

#87 ⬇ Downgrade image and dependencies to v8.0.6
  nut/Dockerfile
  nut/build.json
  nut/config.json
Labels: maintenance

#88 🔨 Change base image to Debian
  nut/DOCS.md
  nut/Dockerfile
  nut/build.json
  nut/config.json
  nut/rootfs/etc/cont-init.d/nut.sh
Labels: major

#94 🔨 Add deadtime configuration option
  nut/DOCS.md
  nut/config.json
  nut/rootfs/etc/cont-init.d/nutclient.sh
  nut/rootfs/etc/nut/upsmon.conf
Labels: documentation, enhancement

#99 📚 Fix formatting
  nut/DOCS.md
Labels: documentation
