Repository hassio-addons/addon-nut, pull requests merged in 2023-03, with the labels that each got.

#281 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  nut/.README.j2
  nut/DOCS.md
Labels: maintenance

#282 ⬆️ Upgrades add-on base image to 6.2.3
  nut/Dockerfile
  nut/build.yaml
Labels: dependencies

#285 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
Labels: maintenance

#290 Set maximum number of connections to 1024
  nut/rootfs/etc/nut/upsd.conf
Labels: enhancement
